-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/checklist_items.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/checklist_items (
  ci_id BLOB NOT NULL,
  ci_page INTEGER UNSIGNED NOT NULL,
  ci_author INTEGER UNSIGNED NOT NULL,
  ci_value BLOB DEFAULT '',
  ci_created BLOB NOT NULL,
  ci_touched BLOB NOT NULL,
  ci_hash BLOB NOT NULL,
  ci_text CLOB DEFAULT NULL,
  PRIMARY KEY(ci_id)
);
