-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/checklist_items.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/checklist_items (
  ci_id VARBINARY(255) NOT NULL,
  ci_page INT UNSIGNED NOT NULL,
  ci_author INT UNSIGNED NOT NULL,
  ci_value VARBINARY(255) DEFAULT '',
  ci_created BINARY(14) NOT NULL,
  ci_touched BINARY(14) NOT NULL,
  ci_hash VARBINARY(32) NOT NULL,
  ci_text LONGTEXT DEFAULT NULL,
  PRIMARY KEY(ci_id)
) /*$wgDBTableOptions*/;
