-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/checklist_items.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE checklist_items (
  ci_id TEXT NOT NULL,
  ci_page INT NOT NULL,
  ci_author INT NOT NULL,
  ci_value TEXT DEFAULT '',
  ci_created TIMESTAMPTZ NOT NULL,
  ci_touched TIMESTAMPTZ NOT NULL,
  ci_hash TEXT NOT NULL,
  ci_text TEXT DEFAULT NULL,
  PRIMARY KEY(ci_id)
);
